apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: rstudio
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/jcampos79/k8s-rstudio.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: data-science

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
